version: '3'
services:
  backend:
    image: royalmist/calcio:latest
    restart: on-failure
    environment:
      - DB_URL=host=db port=5432 user=postgres dbname=calcio password=postgres sslmode=disable
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:13.4-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calcio
