services:
  backend:
    image: royalmist/calcio:latest
    restart: on-failure
    environment:
      - DB_URL=host=db port=5432 user=postgres dbname=calcio password=postgres sslmode=disable
    ports:
      - "4000:4000"
    links:
      - db
  db:
    image: postgres:13.4-alpine
    restart: on-failure
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calcio
volumes:
  db-storage:
